batch_size: 4
iters: 1000

train_dataset:
  type: Dataset
  dataset_root: /root/paddlejob/workspace/train_data/datasets/UDD/train
  train_path: /root/paddlejob/workspace/train_data/datasets/UDD/metadata/train.txt
  num_classes: 5
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: RandomVerticalFlip
    - type: RandomHorizontalFlip
    - type: Normalize
    - type: RandomDistort
  mode: train

val_dataset: 
  type: Dataset
  dataset_root: /root/paddlejob/workspace/train_data/datasets/UDD/val
  val_path: /root/paddlejob/workspace/train_data/datasets/UDD/metadata/val.txt
  num_classes: 5
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
  mode: val

optimizer:
  type: Adam

lr_scheduler:
  type: CosineAnnealingDecay
  learning_rate: 0.0001
  T_max: 333
  last_epoch: 0.5

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 1, 1, 1, 1]

model:
  type: UNetPlusPlus
  in_channels: 3
  num_classes: 5
